### ISSUE TITLE
Show pretty output in notebooks.

### ISSUE THREAD

**Issue by simonpf** [atmtools/typhon#10]
Currently stdout is not visible in IPython notebooks, which can be annoying. One could also think about adding some HTML markup.

**Comment by lkluft** [comment]
Hey Simon,

I have absolutely no experience with handling shared libraries and all the related problems.

But I do not think you have to add full HTML markup. It is more about redirecting the standard output in a way that Jupyter is able to handle it.

Based on [this](https://stackoverflow.com/a/9489139) stackoverflow question,  it is possible to get the output shown in a Jupyter Notebook:

```python
import select
import sys
import os
import time

from typhon.arts.workspace import Workspace



pipe_out, pipe_in = os.pipe()

# save a copy of stdout
stdout = os.dup(1)

# replace stdout with our write pipe
os.dup2(pipe_in, 1)

# check if we have more to read from the pipe
def more_data():
        r, _, _ = select.select([pipe_out], [], [], 0)
        return bool(r)

    
# read the whole pipe
def read_pipe():
        out = ''
        while more_data():
                out += os.read(pipe_out, 1024).decode()

        return out

ws = Workspace()
ws.Print(ws.verbosity)
time.sleep(2)
ws.execute_controlfile('general.arts')

os.dup2(stdout, 1)
print(read_pipe())
```

Maybe this points you in the right direction, otherwise just ignore it :wink:

Cheers,
Lukas

**Comment by simonpf** [comment]
Added in [db34311](https://github.com/atmtools/typhon/commit/db343115b64b7fe7ccbacd80cb1c932a1de23790). It's not pretty but at least ARTS output is now shown in notebooks.

I ended up using a regular file instead of a pipe since a pipe would require an extra process for the reading. Remains to be seen if this is the final solution. Closing for now.
